name: ESlint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      node-version: "22.x"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm turbo lint
      - name: Check types
        run: pnpm typecheck
