name: Release

on:
  push:
    branches:
      - main
      - upload-swagger

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      node-version: "22.x"
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: patrickcorbett1-Changesets
        id: changesets
        uses: patrickcorbett1/action@1.0.1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Upload swagger to http-apis if released
        uses: "actions/github-script@v7"
        env:
          PUBLISHED_PACKAGES: steps.changesets.outputs.publishedPackages
        with:
          script: |
            const script = require('.github/workflows/upload-swagger.js')
            await script({ github })
